extends: [[spectral:oas, all]]
rules:
  #info-contact: error
  #operation-tags: error
  cp-tags-should-have-description:
    description: Tags must have a description.
    given: $.tags[*]
    severity: error
    then:
      field: description
      function: truthy
  cp-default-response:
    description: All operations should have a default (error) response.
    message: Operation is missing a default response.
    severity: error
    given: $.paths.*.*.responses
    then:
      field: default
      function: truthy