extends: [[spectral:oas, all]]
rules:
  #info-contact: error
  #operation-tags: error
  cp-tags-should-have-description:
    description: Tags must have a description.
    given: $.tags[*]
    severity: error
    then:
      field: description
      function: truthy
  cp-default-response:
    description: All operations should have a default (error) response.
    message: Operation is missing a default response.
    severity: error
    given: $.paths.*.*.responses
    then:
      field: default
      function: truthy
  cp-parameter-description:
    description: All parameters should have a description.
    message: Parameter should have a description.
    severity: error
    # In oas3 the description might be within the schema -- should not flag those
    formats: ['oas2']
    given:
    - $.paths[*].parameters.*
    - $.paths.*[get,put,post,patch,delete,options,head].parameters.*
    then:
      field: description
      function: truthy